# -*- coding: utf-8 -*-
"""build_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTDqjC7jvXPoGXitAxJ2EC2hAV1ujgOL
"""

import sqlite3
import pandas as pd

conn=sqlite3.connect("pharmeasy.db")

df1=pd.read_csv('/content/orders_clean.csv')
df2=pd.read_csv('/content/regions_master.csv')

df1.to_sql('orders_clean',conn,if_exists="replace",index=False)
df2.to_sql('regions_master',conn,if_exists="replace",index=False)

conn.commit()

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    """,
    conn,
)

print("Tables currently in pharmeasy.db")

print(tables)

conn.close()