# -*- coding: utf-8 -*-
"""clean-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJEICdjlVDF9iFeQD37rKF_rYK-Fb486
"""

import pandas as pd

df=pd.read_csv('/content/pharmeasy_orders_raw.csv')

df.head()

df.shape

"""Duplicate rows dropping"""

df=df.drop_duplicates()

len(df)

"""Region column normalization"""

df["region"] = df["region"].str.strip().str.title()

print(df['region'])

"""Missing category imputation"""

df["category"]=df["category"].fillna("Unknown")

df["category"].value_counts()["Unknown"]

"""Missing profit imputation"""

df["profit_margin"] = df["profit_inr"] / df["sales_inr"]

category_mean_margin = df.groupby("category")["profit_margin"].mean()

print(category_mean_margin)

missing_profit = df["profit_inr"].isna()

df.loc[missing_profit, "profit_inr"] = (
    df.loc[missing_profit, "sales_inr"]
    * df.loc[missing_profit, "category"].map(category_mean_margin)
).round(2)

"""orders_clean.csv dataset"""

df.to_csv("orders_clean.csv", index=False)

"""Validation"""

df1=pd.read_csv('/content/orders_clean.csv')

df1.head()

df1.columns

required_columns=['order_id', 'order_date', 'region', 'category', 'product', 'quantity',
       'sales_inr', 'profit_inr']

def validate_schema(data,required_cols):
   missing=[column for column in required_cols if column not in data.columns]
   if missing:
    return{'ok':False,'status':'Blocked_schema','missing':missing}
   return{'ok':True,'status':'Validated','rows':len(data)}

validation_1=validate_schema(df1,required_columns)

print(validation_1)

"""Blocked schema"""

df2=df1[['order_id', 'order_date', 'region', 'category', 'product', 'quantity',
       'sales_inr']].copy()

df2

validation_2=validate_schema(df2,required_columns)

print(validation_2)