# -*- coding: utf-8 -*-
"""draft_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3C_bCdod2hvyv9U5e0-aP8NpzwE5RoB
"""

import pandas as pd

metrics=pd.read_csv('/content/metrics.csv')

flagged_regions=pd.read_csv('/content/flagged_regions.csv')

def draft_report_v1(flagged_regions: pd.DataFrame, metrics: pd.DataFrame):
    """
    Produces Context–Insight–Implication (CII) blocks for all unique flagged regions.

    Parameters:
    - flagged_regions (pd.DataFrame): Dataframe containing flag alert indicators.
    - metrics (pd.DataFrame): Dataframe containing exact sales numbers and growth percentages.

    Returns:
    - pd.DataFrame: Dataframe with Region, Context, Insight, and Implication columns.
    """
    # Normalize flag columns to boolean to handle both string 'True' and bool True
    t1_flag_col = 'Flag_Alert_April→May Growth (%)'
    t2_flag_col = 'Flag_Alert_May→June Growth (%)'
    t2_reg_col = 'region.1' if 'region.1' in flagged_regions.columns else 'region'

    t1_mask = flagged_regions[t1_flag_col].astype(str).str.lower() == 'true'
    t2_mask = flagged_regions[t2_flag_col].astype(str).str.lower() == 'true'

    t1_flagged = set(flagged_regions[t1_mask]['region'])
    t2_flagged = set(flagged_regions[t2_mask][t2_reg_col])

    # Union of all unique flagged regions (8 regions total)
    unique_flagged = sorted(list(t1_flagged.union(t2_flagged)))

    report_data = []

    for region in unique_flagged:
        # Fetch corresponding metrics row
        row = metrics[metrics['region'] == region].iloc[0]

        apr_sales = row['April 2026 Sales (INR)']
        may_sales = row['May 2026 Sales (INR)']
        june_sales = row['June 2026 Sales (INR)']
        t1_growth = row['April→May Growth (%)']
        t2_growth = row['May→June Growth (%)']

        is_t1 = region in t1_flagged
        is_t2 = region in t2_flagged

        # 1. Context
        context = (
            f"{region} recorded monthly sales of INR {apr_sales:,.2f} in April 2026, "
            f"INR {may_sales:,.2f} in May 2026, and INR {june_sales:,.2f} in June 2026."
        )

        # 2. Insight
        if is_t1 and is_t2:
            insight = (
                f"The region was flagged in both transitions, exhibiting a growth rate of "
                f"{t1_growth:+.2f}% from April to May and {t2_growth:+.2f}% from May to June."
            )
        elif is_t1:
            insight = (
                f"The region was flagged during the April→May transition with a growth rate of "
                f"{t1_growth:+.2f}%, while the May→June transition recorded a growth rate of {t2_growth:+.2f}%."
            )
        else:
            insight = (
                f"The region was flagged during the May→June transition with a growth rate of "
                f"{t2_growth:+.2f}%, following an April→May growth rate of {t1_growth:+.2f}%."
            )

        # 3. Implication
        if is_t1 and is_t2:
            implication = (
                f"Consecutive period-over-period volatility across both transitions (moving from "
                f"INR {apr_sales:,.2f} to INR {may_sales:,.2f} and then to INR {june_sales:,.2f}) requires "
                f"detailed root-cause operational analysis and inventory recalibration."
            )
        elif is_t1:
            implication = (
                f"Significant fluctuation during the April→May transition (changing from "
                f"INR {apr_sales:,.2f} to INR {may_sales:,.2f}) necessitates targeted demand planning ahead "
                f"of future reporting cycles."
            )
        else:
            implication = (
                f"Performance shifts during the May→June transition (changing from "
                f"INR {may_sales:,.2f} to INR {june_sales:,.2f}) warrant strategic review to ensure steady sales trajectory."
            )

        report_data.append({
            'Region': region,
            'Context': context,
            'Insight': insight,
            'Implication': implication
        })

    return pd.DataFrame(report_data)

# Generate output dataframe:
report_df = draft_report_v1(flagged_regions, metrics)

# To view output directly in terminal/console:
for idx, row in report_df.iterrows():
    print(f"=== {row['Region']} ===")
    print(f"Context:     {row['Context']}")
    print(f"Insight:     {row['Insight']}")
    print(f"Implication: {row['Implication']}\n")