# -*- coding: utf-8 -*-
"""metrics_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxEHWjfezU9LPv0QaDyXQXIT7f16Jfkn
"""

import sqlite3

import pandas as pd

df = pd.read_csv("/content/metrics.csv")

df

df.columns

"""compute_percentage_change_v1(current, previous) — handles division-by-zero by returning 0."""

def compute_percentage_change_v1(current,previous):
  if previous is None or current is None:
    return 0.0

  try:
    current=float(current)
    previous-float(previous)
  except (ValueError, TypeError):
        return 0.0

  if previous == 0:
      return 0.0

  return ((current - previous) / previous) * 100.0

print(compute_percentage_change_v1('May→June Growth (%)','April→May Growth (%)'))

def flag_significant_regions_v1(df, target_cols, threshold=8):
  df_flagged = df.copy()
  if isinstance(target_cols, str):
        target_cols = [target_cols]

  for col in target_cols:
        # Create a clean column name for the output flag
        flag_col_name = f"Flag_Alert_{col}"

        # Check if absolute MoM change exceeds the threshold
        df_flagged[flag_col_name] = df_flagged[col].abs() > threshold

  return df_flagged

growth_columns = ['April→May Growth (%)', 'May→June Growth (%)']

df_flagged = flag_significant_regions_v1(df, target_cols=growth_columns, threshold=8)

result=df_flagged[['region', 'April→May Growth (%)', 'Flag_Alert_April→May Growth (%)', 'region','May→June Growth (%)', 'Flag_Alert_May→June Growth (%)']]
print(result)

result.to_csv("flagged_regions.csv", index=False)

import json
import os

def save_state_v1(month_summary: dict, path: str) -> None:
    """
    Persists a month's computed summary dictionary to disk as a JSON file.
    Automatically creates parent directories if they do not exist.
    """
    # Ensure directory path exists
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(month_summary, f, indent=4, ensure_ascii=False)
    print(f"State successfully saved to: {path}")

def load_previous_state_v1(path: str) -> dict:
    """
    Reloads a previously saved monthly summary JSON file.

    Returns:
        dict: The reloaded month summary dictionary.

    Raises:
        FileNotFoundError: If no saved state exists at the specified path.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"No state file found at: {path}")

    with open(path, 'r', encoding='utf-8') as f:
        month_summary = json.load(f)

    print(f"State successfully loaded from: {path}")
    return month_summary

april_raw_df=df[['region', 'April 2026 Sales (INR)']]

april_summary = {
    'month': 'April 2026',
    'region_sales': april_raw_df.set_index('region')['April 2026 Sales (INR)'].to_dict()
}

april_state_path = "states/april_2026_summary.json"
save_state_v1(april_summary, april_state_path)

april_prev_state = load_previous_state_v1(april_state_path)

may_raw_df = df[['region', 'May 2026 Sales (INR)']]

may_raw_df['April 2026 Sales (INR)'] = may_raw_df['region'].map(april_prev_state['region_sales'])

may_raw_df['April→May Growth (%)'] = (
    (may_raw_df['May 2026 Sales (INR)'] - may_raw_df['April 2026 Sales (INR)'])
    / may_raw_df['April 2026 Sales (INR)']
) * 100

print("\n--- May Incremental Analysis Result ---")
print(may_raw_df[['region', 'April 2026 Sales (INR)', 'May 2026 Sales (INR)', 'April→May Growth (%)']])

may_summary = {
    'month': 'May 2026',
    'region_sales': may_raw_df.set_index('region')['May 2026 Sales (INR)'].to_dict()
}
save_state_v1(may_summary, "states/may_2026_summary.json")