# -*- coding: utf-8 -*-
"""queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggGDMUPU-F4SAkgDpUmntyFTyA3AlsPo
"""

import sqlite3

import pandas as pd

conn=sqlite3.connect("pharmeasy.db")

"""Row count check"""

query_left = """
    SELECT COUNT(*) AS cnt
    FROM regions_master r
    LEFT JOIN orders_clean o ON r.region = o.region
"""
query_inner = """
    SELECT COUNT(*) AS cnt
    FROM regions_master r
    INNER JOIN orders_clean o ON r.region = o.region
"""

left_cnt=pd.read_sql_query(query_left,conn).iloc[0]["cnt"]
inner_cnt=pd.read_sql_query(query_inner,conn).iloc[0]["cnt"]

print(f"LEFT JOIN count: {left_cnt:,}")
print(f"INNER JOIN count:{inner_cnt:,}")
print(f"Unmatched Regions:{left_cnt - inner_cnt:,}")

"""Duplicate key check"""

query1 = """
    SELECT order_id, COUNT(*) AS occurrences
    FROM orders_clean
    GROUP BY order_id
    HAVING COUNT(*) > 1;
"""

duplicates = pd.read_sql_query(query1, conn)

if duplicates.empty:
    print("PASSED: No duplicate order_id entries found in orders_clean.")
else:
    print(
        f"FAILED: Found {len(duplicates):,} duplicate order_id key(s) in orders_clean:"
    )
    print(duplicates)

"""Null check"""

query2 = """
    SELECT
        r.region,
        COUNT(*) AS count_star,
        COUNT(o.order_id) AS count_order_id,
        CASE
            WHEN COUNT(*) <> COUNT(o.order_id) THEN 'DISAGREE (Zero-Order Region)'
            ELSE 'AGREE'
        END AS status
    FROM regions_master r
    LEFT JOIN orders_clean o
        ON r.region = o.region
    GROUP BY r.region
    HAVING COUNT(*) <> COUNT(o.order_id);
"""

mismatches = pd.read_sql_query(query2, conn)

if mismatches.empty:
    print("ALL AGREE: Every region in regions_master has at least one order in orders_clean.")
else:
    print(f"DISAGREEMENT FOUND in {len(mismatches)} region(s):")
    print(mismatches.to_string(index=False))

"""Per region order count"""

query3 = """
    SELECT
        r.region,
        COUNT(o.order_id) AS total_orders
    FROM regions_master r
    LEFT JOIN orders_clean o
        ON r.region = o.region
    GROUP BY r.region
    ORDER BY total_orders ASC;
"""

region_counts = pd.read_sql_query(query3, conn)

print("Per-Region Order Counts (Ascending):")
print(region_counts.to_string(index=False))

"""Region - Month metrics and MoM growth"""

query4 = """
    WITH monthly_sales AS (
        SELECT
            r.region,
            strftime('%Y-%m', o.order_date) AS order_month,
            SUM(o.sales_inr) AS total_sales_inr
        FROM regions_master r
        INNER JOIN orders_clean o ON r.region = o.region
        WHERE o.order_date >= '2026-04-01'
          AND o.order_date < '2026-07-01'
        GROUP BY r.region, strftime('%Y-%m', o.order_date)
    ),
    sales_with_lag AS (
        SELECT
            region,
            order_month,
            total_sales_inr,
            LAG(total_sales_inr) OVER (
                PARTITION BY region
                ORDER BY order_month
            ) AS prev_month_sales
        FROM monthly_sales
    )
    SELECT
        region,
        order_month,
        total_sales_inr,
        ROUND(
            (total_sales_inr - prev_month_sales) * 100.0 / prev_month_sales,
            2
        ) AS mom_growth_pct
    FROM sales_with_lag;
"""

df = pd.read_sql_query(query4, conn)

"""pivot table"""

sales_pivot = df.pivot(
    index="region", columns="order_month", values="total_sales_inr"
)
growth_pivot = df.pivot(
    index="region", columns="order_month", values="mom_growth_pct"
)

result = pd.DataFrame(
    {
        "April 2026 Sales (INR)": sales_pivot["2026-04"],
        "May 2026 Sales (INR)": sales_pivot["2026-05"],
        "June 2026 Sales (INR)": sales_pivot["2026-06"],
        "April→May Growth (%)": growth_pivot["2026-05"],
        "May→June Growth (%)": growth_pivot["2026-06"],
    }
).reset_index()

print("Region MoM Sales Performance:")
print(result.to_string(index=False))

result.to_csv("metrics.csv", index=False)