# -*- coding: utf-8 -*-
"""review-gate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUWHfXAiBgyRdkj65b9r3l0ZhTsRflBT
"""

import json
import uuid
import os
from datetime import datetime

def review_gate_v1(report: dict, decision: str, reviewer_note: str = "") -> dict:
    """
    Review-gate tool that validates decision input, updates report permissions for
    downstream/external usage, and appends a structured record to audit_log.jsonl.

    Parameters:
    - report (dict): Report dictionary containing at minimum 'region' and optional 'run_id'.
    - decision (str): Must be one of {"approve", "edit", "reject"}.
    - reviewer_note (str): Optional comments or reasoning provided by the reviewer.

    Returns:
    - dict: Updated report dictionary with review status and downstream permission flags.

    Raises:
    - ValueError: If `decision` is outside the allowed set {"approve", "edit", "reject"}.
    """
    valid_decisions = {"approve", "edit", "reject"}

    # 1. Validate decision input
    if not isinstance(decision, str) or decision.lower() not in valid_decisions:
        raise ValueError(
            f"Invalid decision '{decision}'. Must be one of: {sorted(list(valid_decisions))}"
        )

    clean_decision = decision.lower()

    # 2. Determine downstream/external usage permission
    # Reports are allowed for external use ONLY when explicitly approved
    allow_external_use = (clean_decision == "approve")

    # 3. Create updated report dictionary
    updated_report = report.copy()
    updated_report["review_status"] = clean_decision
    updated_report["allow_external_use"] = allow_external_use
    updated_report["reviewer_note"] = reviewer_note

    # Extract operational metadata
    region = report.get("region", "UNKNOWN")
    run_id = report.get("run_id", str(uuid.uuid4()))
    timestamp = datetime.utcnow().isoformat() + "Z"

    # 4. Construct audit log record with all 5 required fields
    audit_entry = {
        "timestamp": timestamp,
        "run_id": run_id,
        "region": region,
        "decision": clean_decision,
        "reviewer_note": reviewer_note
    }

    # Append single line record to audit_log.jsonl
    with open("audit_log.jsonl", "a", encoding="utf-8") as f:
        f.write(json.dumps(audit_entry) + "\n")

    return updated_report


# =====================================================================
# TEST HARNESS
# =====================================================================
if __name__ == "__main__":
    # Clean up prior test logs if present
    if os.path.exists("audit_log.jsonl"):
        os.remove("audit_log.jsonl")

    print("================ TEST HARNESS EXECUTION ================\n")

    test_reports = [
        {"region": "Guntur", "run_id": "RUN-2026-001", "sales": 138738.93},
        {"region": "Hyderabad", "run_id": "RUN-2026-002", "sales": 294088.56},
        {"region": "Visakhapatnam", "run_id": "RUN-2026-003", "sales": 100735.57}
    ]

    decisions_and_notes = [
        ("approve", "Metrics verified against source logs. Approved for publication."),
        ("edit", "Re-verify May sales surge due to potential duplicate bulk order entries."),
        ("reject", "Unexplained extreme variance detected. Rejecting report for audit.")
    ]

    # Exercise all 3 valid decision paths
    for report, (dec, note) in zip(test_reports, decisions_and_notes):
        print(f"--- Reviewing Region: {report['region']} ---")
        print(f"BEFORE State: {report}")

        updated = review_gate_v1(report, dec, reviewer_note=note)

        print(f"AFTER State : {updated}\n")

    # Exercise invalid decision path (Validation Check)
    print("--- Testing Invalid Decision Argument ---")
    try:
        review_gate_v1({"region": "Bengaluru"}, "invalid_option")
    except ValueError as e:
        print(f"Validation Error caught successfully: {e}\n")

    # Read back and verify audit_log.jsonl
    print("--- Verifying audit_log.jsonl Contents ---")
    with open("audit_log.jsonl", "r", encoding="utf-8") as f:
        logs = [json.loads(line) for line in f]

    for i, log in enumerate(logs, 1):
        print(f"Audit Entry #{i}: {log}")